repos:
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.8.0'
  hooks:
  -   id: mypy
      files: ^(src/)
      additional_dependencies:
      - "pydantic>=2.5.3"
      args: [--ignore-missing-imports]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.13
  hooks:
    - id: ruff
    - id: ruff-format
- repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  rev: v1.3.1
  hooks:
  -   id: python-safety-dependencies-check
      files: pyproject.toml