services:
  database:
    container_name: database
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
#      POSTGRES_DB: ${DB_NAME}
      POSTGRES_DB: test_euroget
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/database_dump.sql