"""new

Revision ID: 77a728336173
Revises: 4bc258fb6d17
Create Date: 2024-01-14 22:33:52.247522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a728336173'
down_revision = '4bc258fb6d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.Text(), nullable=True),
    sa.Column('cause', sa.Text(), nullable=True),
    sa.Column('is_part_of_instalment', sa.Boolean(), nullable=True),
    sa.Column('instalment_id', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_payments_id'), 'failed_payments', ['id'], unique=False)
    op.create_index(op.f('ix_failed_payments_user_id'), 'failed_payments', ['user_id'], unique=False)
    op.add_column('tokens', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tokens', sa.Column('is_valid', sa.Boolean(), nullable=False))
    op.alter_column('tokens', 'gc_ob_access_token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tokens', 'gc_ob_refresh_token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_tokens_created_at'), 'tokens', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_created_at'), table_name='tokens')
    op.alter_column('tokens', 'gc_ob_refresh_token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tokens', 'gc_ob_access_token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('tokens', 'is_valid')
    op.drop_column('tokens', 'created_at')
    op.drop_index(op.f('ix_failed_payments_user_id'), table_name='failed_payments')
    op.drop_index(op.f('ix_failed_payments_id'), table_name='failed_payments')
    op.drop_table('failed_payments')
    # ### end Alembic commands ###
